theme = "terminal"
baseURL = "https://dispatches.fromthefrontier.xyz/"
languageCode = "en-us"
title = "Dispatches from the Frontier"
canonifyURLs = true
uglyURLs = false

[params]
  contentTypeName = "posts"
  themeColor = "green"
  themeVariant = "terminal-light"
  showMenu = true
  logo = "Dispatches from the Frontier"
