theme = "terminal"
baseURL = "https://dispatches.fromthefrontier.xyz/"
languageCode = "en-us"
title = "Dispatches from the Frontier"

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenu = true

